### ISSUE TITLE
[命令行工具] 除用户添加外所有功能均无法使用

### ISSUE THREAD

**Issue by djkcyl** [beetcb/cea#13]
删除用户：
`(node:17564) UnhandledPromiseRejectionWarning: ReferenceError: get is not defined
    at i.deleteUser (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:14:1985)
    at C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:21:234
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

配置学校：
`(node:16216) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at c.schoolApi (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:14:3281)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async c.init (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:14:2330)
    at async C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:21:277
(node:16216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

签到：
`(node:10616) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'login' of undefined
    at module.exports (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:8:456)
    at t (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:12:210)
    at C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:12:616
    at Array.map (<anonymous>)
    at r.e.handleCookie (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:12:561)
    at C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:18:220
    at Object.parcelRequire.PTk1.../src/index (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:18:266)
    at f (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:3:468)
    at p (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:3:544)
    at C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:21:376
(node:10616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by djkcyl** [comment]
学校是湖北工业职业技术学院
https://hbgyzy.campusphere.net/

**Comment by yaonyan** [comment]
是一个插件升级带来的报错 @djkcyl

**Comment by djkcyl** [comment]
> 是一个插件升级带来的报错 @djkcyl

哪有什么办法解决吗，给插件降级？

**Comment by yaonyan** [comment]
我更新一下，发布一个新的版本，除 CLI 外其它的功能应该是完好的

**Comment by djkcyl** [comment]
好的

**Comment by yaonyan** [comment]
好了 (～￣▽￣)～ @djkcyl  请安装这个版本 `@beetcb/cea@2.0.9`，如果再有问题就是学校的适配性问题，我会考虑适配

**Comment by djkcyl** [comment]
我去试试

**Comment by djkcyl** [comment]
用户删除可以用了，学校设置-s和sign依然不能使用

学校设置：
(node:15804) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at c.schoolApi (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:14:3284)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async c.init (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:14:2332)
    at async C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:21:277
(node:15804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

签到
(node:8648) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'login' of undefined
    at module.exports (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:8:456)
    at t (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:12:210)
    at C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:12:616
    at Array.map (<anonymous>)
    at r.e.handleCookie (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:12:561)
    at C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:18:220
    at Object.parcelRequire.PTk1.../src/index (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:18:266)
    at f (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:3:468)
    at p (C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:3:544)
    at C:\Users\cyl\AppData\Roaming\npm\node_modules\@beetcb\cea\dist\cli.js:21:376
(node:8648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yaonyan** [comment]
因为你们学校 id 区域竟然是
![image](https://user-images.githubusercontent.com/63141491/109421307-b256d580-7a11-11eb-8d47-cc4eaf4771c9.png)
![image](https://user-images.githubusercontent.com/63141491/109421342-cd294a00-7a11-11eb-9f92-6da8c1a08dc4.png)
其它大多数学校都是英文简称 `(*>﹏<*)′

**而且登录表单不一样，有时间我会兼容**

**Comment by djkcyl** [comment]
所以说用数字id就没问题了吗

**Comment by djkcyl** [comment]
哦好的，谢谢啦

**Comment by yaonyan** [comment]
@djkcyl  而且登录表单不一样，有时间我会兼容

**Comment by yaonyan** [comment]
你看看我 README 那个最后感谢里  wisedu-unified-login-api  项目兼不兼容，它的适配性很好

**Comment by djkcyl** [comment]
我去试试

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/109422140-3a8aaa00-7a15-11eb-85f8-db8b4abdb547.png)

应该是不行吧

**Comment by yaonyan** [comment]
试试这个 [url](https://hbgyzy.campusphere.net/iap/login)，应该是可以的，我看了代码

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/109422408-5f335180-7a16-11eb-9d29-95826c25be5f.png)

**Comment by yaonyan** [comment]
![image](https://user-images.githubusercontent.com/63141491/109422599-35c6f580-7a17-11eb-984c-c5eec52d3aa2.png)

大概像这样，如果确实不行，有时间我会看看的，(你也可以试着爬一爬，看看有没有可能提个 PR)

**Comment by yaonyan** [comment]
@djkcyl  各个学校不一样，导致这种爬虫类的开发是很杂的，适配性很低是正常的，不要气馁，多尝试 😂

**Comment by beetcb** [comment]
@djkcyl  @beetcb/cea@2.1.5 支持了这种登录模式，先关掉这个 Issue （缺少回复）

**Comment by yaonyan** [comment]
@djkcyl @beetcb/cea@2.1.5 支持了这种登录模式，先关掉这个 Issue （缺少回复）

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/111901326-66c4a400-8a72-11eb-967a-5f95f547d5cc.png)
如果添加用户时信息为空则会导致这个问题

**Comment by yaonyan** [comment]
可能本地配置比较乱，建议执行一次 `cea rm all` 重新配置，（因为这种问题估计也难复现 @djkcyl）
