### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'load' of undefined

### ISSUE THREAD

**Issue by CncCbz** [beetcb/cea#17]
![image](https://user-images.githubusercontent.com/43227065/111871057-3d007400-89c3-11eb-9f61-afd00a9f40f7.png)
按照README写的demo无法获取到conf？

**Comment by yaonyan** [comment]
目前版本的 API 有些 Breaking Changes：
我的 repo 里有个现成的更好的例子：
https://github.com/beetcb/cea/blob/730481c6f0a2326252aa78bba59827cc088e2c01/TEST/dcampus.js#L1-L25
@CncCbz

**Comment by CncCbz** [comment]
> 目前版本的 API 有些 Breaking Changes：
> 我的 repo 里有个现成的更好的例子：
> https://github.com/beetcb/cea/blob/730481c6f0a2326252aa78bba59827cc088e2c01/TEST/dcampus.js#L1-L25
> 
> 
> @CncCbz

我尝试使用这个demo，但是好像加密密码阶段的key获取不到，是undefined，请问是我哪里没有设置对吗？
![image](https://user-images.githubusercontent.com/43227065/111873303-9e781100-89ca-11eb-9c4d-2ef4bbf4442b.png)

**Comment by yaonyan** [comment]
具体要看学校登录页面了，不同学校不一样 (～￣▽￣)～

这是（也就是你 Debug 的代码）是登录的核心代码：
https://github.com/beetcb/cea/blob/a39a9a2751076c143988dc15c79cc222f78b29c3/crawler/casLogIn.js#L48-L51

你看看你们学校是什么元素，还有需不需要加密密码 @CncCbz

**Comment by yaonyan** [comment]
@CncCbz  忘说了，也可以贴一下学校名字，我明天看看 🦄

**Comment by CncCbz** [comment]
> @CncCbz 忘说了，也可以贴一下学校名字，我明天看看 🦄

宁波大学o(╥﹏╥)o，我比较菜，谢谢大佬

**Comment by yaonyan** [comment]
@CncCbz  害，不是大佬，其实多花点时间看看应该就可以成功。这是开源项目，随时欢迎交流（贡献）

**Comment by yaonyan** [comment]
@CncCbz 更新到 cea@2.1.4，适配性更强，你使用你的账号测试一下，看看有没有问题

如果登录失败，看看登录提交的表单和下面是否类似：

![image](https://user-images.githubusercontent.com/63141491/111892363-c0f34400-8a35-11eb-89b7-c3f3ffcf6108.png)

**Comment by CncCbz** [comment]
@beetcb 表单没有问题（图1），但是返回的执行recook判断时，返回的是false（图二）我用手动post了一下，response headers也是没有set-cookies的
![image](https://user-images.githubusercontent.com/43227065/111894438-afb23380-8a45-11eb-8bb6-1805674987aa.png)
![image](https://user-images.githubusercontent.com/43227065/111894624-4e8b5f80-8a47-11eb-8651-c7788ba5f366.png)

**Comment by yaonyan** [comment]
> 如果登录失败，看看登录提交的表单和下面是否类似：

这里是说去浏览器手动成功登录一下看看表单是什么样子的，再和本地对比下 @CncCbz 

愿意的话也可以把账号发我邮箱，帮你看看 i@beetcb.com

**Comment by beetcb** [comment]
![image](https://user-images.githubusercontent.com/63141491/111895563-7cc06d80-8a4e-11eb-9541-34498a7f3bd1.png)

这一步判断我觉得很有问题（我是把2种cookie分开了的），应该问题出在这儿（就是下次 POST 的时候之前的 cookie 没正确处理）

**Comment by yaonyan** [comment]
@CncCbz  最新版本已修复，先 close 掉了!
