### ISSUE TITLE
作者大大，似乎HENU不支持登陆，您有兴趣研究一下吗

### ISSUE THREAD

**Issue by kuriyamamiraitowa** [beetcb/cea#30]
START RequestId: 646f306d-af4a-455e-8620-fe95d5b23c84

Event RequestId: 646f306d-af4a-455e-8620-fe95d5b23c84

2021-05-21T23:32:38.066Z 646f306d-af4a-455e-8620-fe95d5b23c84 尝试从配置文件加载配置

2021-05-21T23:32:38.067Z 646f306d-af4a-455e-8620-fe95d5b23c84 用户 one 已加载

2021-05-21T23:32:38.436Z 646f306d-af4a-455e-8620-fe95d5b23c84 你的学校 河南大学 已完成设定

2021-05-21T23:32:39.119Z 646f306d-af4a-455e-8620-fe95d5b23c84 用户one：登录失败，Unauthorized

2021-05-21T23:32:39.119Z 646f306d-af4a-455e-8620-fe95d5b23c84 用户one：无效的 Cookie，尝试重新登录

2021-05-21T23:32:39.751Z 646f306d-af4a-455e-8620-fe95d5b23c84 用户one：登录失败，Unauthorized

2021-05-21T23:32:39.754Z 646f306d-af4a-455e-8620-fe95d5b23c84 ┌─────────┬──────────────────┐

│ (index) │       签到结果       │

├─────────┼──────────────────┤

│   one   │ '今日签到任务已完成，取消签到' │

└─────────┴──────────────────┘

END RequestId: 646f306d-af4a-455e-8620-fe95d5b23c84

Report RequestId: 646f306d-af4a-455e-8620-fe95d5b23c84 Duration:1694ms Memory:256MB MemUsage:47.5859MB

**Comment by yaonyan** [comment]
本来是可以的，最近上游（今日校园）的登录方式又改了：学校那边可以登录，但是跳转到 campuphere 地址不对，🍪 没拿到 @kuriyamamiraitowa 

这两天会修复的

**Comment by kuriyamamiraitowa** [comment]
> 本来是可以的，最近上游（今日校园）的登录方式又改了：学校那边可以登录，但是跳转到 campuphere 地址不对，🍪 没拿到 @kuriyamamiraitowa
> 
> 这两天会修复的

THX FOR UR REPLY, HOPE TO SEE UR NEW CODE ! HAVE A NICE DAY :)

**Comment by yaonyan** [comment]
@kuriyamamiraitowa 应该可以了，请帮忙测试下

更新方法 -> https://github.com/beetcb/cea/issues/27 ，你用腾讯云的话只需要点安装依赖就行了

**Comment by kuriyamamiraitowa** [comment]
> 更新方法 -> #27 ，你用腾讯云的话只需要点安装依赖就行了

测试结果：失败
返回结果：

{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"b9a8dbc8-df76-4214-b50d-ca11b4223723","stackTrace":"TypeError: s.text is not a function\n    at c.schoolApi (/var/user/node_modules/@beetcb/cea/dist/index.js:18:3497)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","statusCode":430}

摘要
请求ID：b9a8dbc8-df76-4214-b50d-ca11b4223723

运行时间：1048ms

计费时间：1100ms

运行内存：47.41796875MB

日志
START RequestId: b9a8dbc8-df76-4214-b50d-ca11b4223723

Event RequestId: b9a8dbc8-df76-4214-b50d-ca11b4223723

2021-05-22T14:30:41.081Z b9a8dbc8-df76-4214-b50d-ca11b4223723 尝试从配置文件加载配置

2021-05-22T14:30:41.081Z b9a8dbc8-df76-4214-b50d-ca11b4223723 用户 one 已加载

END RequestId: b9a8dbc8-df76-4214-b50d-ca11b4223723

Report RequestId: b9a8dbc8-df76-4214-b50d-ca11b4223723 Duration:1048ms Memory:256MB MemUsage:47.418MB


作者大大， 这时候没有签到任务，晚签已经完成了，运行结果是这样的，是正常的吗

**Comment by yaonyan** [comment]
这个报错意味着学校都还没配置成功，是不是哪里配置错了导致报错 （还没到登录阶段呢😂）

@kuriyamamiraitowa

**Comment by kuriyamamiraitowa** [comment]
大大，今天我没在学校没法测试下午回去 你有联系方式吗 我们可以约个时间 也可以我私聊给你个账号测试一下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月22日(星期六) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [beetcb/cea] 作者大大，似乎HENU不支持登陆，您有兴趣研究一下吗 (#30)

**Comment by yaonyan** [comment]
好，邮箱：i@beetcb.com

**Comment by kuriyamamiraitowa** [comment]
1819010121  YUDI5678   ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月23日(星期天) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [beetcb/cea] 作者大大，似乎HENU不支持登陆，您有兴趣研究一下吗 (#30)

**Comment by yaonyan** [comment]
@kuriyamamiraitowa 你就这样公开出来啦，不太好吧，我帮你删掉了

**Comment by yaonyan** [comment]
OK @kuriyamamiraitowa 

命令行测试成功，不小心帮你签了哈 😂：

![image](https://user-images.githubusercontent.com/63141491/119247761-014e7a00-bbbf-11eb-98a4-aceeff5b70a0.png)

**Comment by kuriyamamiraitowa** [comment]
> OK @kuriyamamiraitowa
> 
> 命令行测试成功，不小心帮你签了哈 😂：
> 
> ![image](https://user-images.githubusercontent.com/63141491/119247761-014e7a00-bbbf-11eb-98a4-aceeff5b70a0.png)

刚才试了一下可以模拟登陆了，感谢您的更新和耐心解答 like&star :)
