### ISSUE TITLE
关于HENU登录问题

### ISSUE THREAD

**Issue by git268** [beetcb/cea#31]
// if we got here, this site definitely uses AJAX to get those props (`iap`)
    // we need to request those properties manually
    headers.Referer = res.headers.get('location')
    const ltWrapper = new URL(headers.Referer).search
    if (Object.keys(hiddenInputNameValueMap).length === 0) {
      res = await fetch(`${school.casOrigin}${schoolEdgeCases.lt}${ltWrapper}`)
      const { result } = await res.json()
      Object.defineProperties(hiddenInputNameValueMap, {
        lt: { value: result._lt, enumerable: true },
        needCaptcha: { value: result.needCapt, enumerable: true },
        dllt: { value: '', enumerable: true },
        iap: { value: true, enumerable: true },
      })
      // seems dcampus forgot to impl _encryptSalt, comment it out temporarily
      // pwdSalt = result._encryptSalt
    }
此处想知道具体执行逻辑，我以前做过HENU的模拟登录，更新后debug发现在获取MOD_AUTH_CAS这个cookie无返回，获取HWWAFSESID会返回一个errorMessage:程序出现错误，非ajax方式直接跳转到错误处理页面

**Comment by yaonyan** [comment]
@git268 跟那个代码没关系哈，那是 CLOUD 的实现

NOTCLOUD 大致如下步骤：
1. 首先我们获取 campusphere 那边的 session
 https://github.com/beetcb/cea/blob/1ed66998955975366dd03e9f556d91a204e5f060/src/crawler/casLogIn.js#L36
2. 这个 session 会被作为 url 参数，重定向到学工系统统一登录那个界面，这我们又拿到学工这边的 session
3. 然后有些验证码处理
https://github.com/beetcb/cea/blob/1ed66998955975366dd03e9f556d91a204e5f060/src/crawler/casLogIn.js#L92-L130
4. 然后正确构建登录表单
https://github.com/beetcb/cea/blob/1ed66998955975366dd03e9f556d91a204e5f060/src/crawler/casLogIn.js#L82-L90

5. 然后有两个跳转：
https://github.com/beetcb/cea/blob/1ed66998955975366dd03e9f556d91a204e5f060/src/crawler/casLogIn.js#L150-L154

比之前麻烦多了，如果还是从学工开始的话，重定向更多（我这次改成从 `campusphere` 开始）

**Comment by yaonyan** [comment]
`Node.js` 没有一个比较好的 Session 管理库，所以我手写的 Cookie 处理，比较麻烦。

`Python` 的 `Request` 库应该更方便
