### ISSUE TITLE
我是小白，在腾讯云中测试失败，希望作者大大能指点一下

### ISSUE THREAD

**Issue by lMaiZhao** [beetcb/cea#32]
返回结果：{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"49ef2437-b85a-4bc0-ad82-a7ceb8afcbeb","stackTrace":"TypeError: a.text is not a function\n    at c.schoolApi (/var/user/node_modules/@beetcb/cea/dist/index.js:18:3487)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","statusCode":430}
日志：START RequestId: 49ef2437-b85a-4bc0-ad82-a7ceb8afcbeb

Event RequestId: 49ef2437-b85a-4bc0-ad82-a7ceb8afcbeb

2021-05-25T16:04:08.360Z 49ef2437-b85a-4bc0-ad82-a7ceb8afcbeb ⚠  警示        尝试从配置文件加载配置

2021-05-25T16:04:08.361Z 49ef2437-b85a-4bc0-ad82-a7ceb8afcbeb ✔  成功        用户 one 已加载

END RequestId: 49ef2437-b85a-4bc0-ad82-a7ceb8afcbeb

Report RequestId: 49ef2437-b85a-4bc0-ad82-a7ceb8afcbeb Duration:1081ms Memory:256MB MemUsage:51.6562MB

**Comment by yaonyan** [comment]
@lMaiZhao 请提供一下能够复现这个问题的配置文件（敏感信息可以忽略），初步判断为学校配置有问题

**Comment by yaonyan** [comment]
@lMaiZhao 项目迁移到 https://github.com/ceajs/cea ，有问题请到新仓库交流
